language: go

go:
  - 1.6.2
  - tip

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)